resources:
  - deployment.yml
  - service.yml
  - postgres-deployment.yml
  - postgres-service.yml
  - secret.yml

images:
  - name: elponcho/sampleapp
    newTag: main

# patchesStrategicMerge:
#   - patch-deployment.yml
