apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-deployment-migrate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
        - name: sampleapp
          image: elponcho/sampleapp:main
          command: ["python", "manage.py", "migrate"]
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:samplepassword@postgres-service/postgres"
