version: '3'

tasks:
  docker-build:
    cmds:
      - docker build -t sampleapp:latest .
  docker-run:
    cmds:
      - docker run -it --rm sampleapp:latest
  start:
    cmds:
      - python3 manage.py migrate
      - python3 manage.py collectstatic
      - python3 manage.py runserver
