apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vbystr-certificate
spec:
  dnsNames:
  - 'vbystr.dacdevops.ru'
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: vbystr-cert