apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-deployment
spec:
  template:
    spec:
      containers:
        - name: sampleapp
          command: ["gunicorn", "--bind", "0.0.0.0:8000", "sampleproject.wsgi"]
